name: memoris-plugin
version: 1.2
author: Tinoou
main: fr.tinoou.memoris.Main
commands:
  money:
    description: Show your wallet
  pay:
    description: Pay someone
  givemoney:
    description: Gives money to someone
    permission: moneyadmin.use